### ISSUE TITLE
Dealing with checkbox/radio groups

### ISSUE THREAD

**Issue by alnassif** [spatie/laravel-blade-x#104]
Hi there, 

I'm still new to Laravel and the Blade X package, though i can't for the life of me figure out how to structure my custom checkbox group field and the view model to deal with check boxes that are checked. If someone can provide me with some assistance that would be great.

**Comment by freekmurze** [comment]
My 2 cents: if your new to Laravel and want to use Blade X type of components, wait a bit until the release of Laravel 7 (will be out early march). It'll will have native support for Blade components.
