### ISSUE TITLE
Pulling out model logic out of blade-x component

### ISSUE THREAD

**Issue by JeffreyDavidson** [spatie/laravel-blade-x#106]
This is my date-field component. If you notice inside of the value attribute of the input element it has a value that is situational to the form that it is on. What can I do so that I can pull that logic out so that the value is determined out of the component?

```
<field-label :for="$name" :label="$label ?? ''" />

<div class="kt-input-icon kt-input-icon--right">
    <input 
        type="text" 
        class="form-control @error($name) is-invalid @enderror"
        name="{{ $name }}" 
        placeholder="Enter {{ $label }}"
        value="{{ old($name, optional($employee->employment->started_at ?? null)->toDateTimeString()) }}"
        data-datetimepicker 
        data-input
    >
    <span class="kt-input-icon__icon kt-input-icon__icon--right">
        <span><i class="flaticon-calendar-with-a-clock-time-tools"></i></span>
    </span>
    @error($name)
        <form-error name="{{ $name }}" />
    @enderror
</div>
```

**Comment by freekmurze** [comment]
Take a look at view models: https://docs.spatie.be/laravel-blade-x/v2/advanced-usage/transforming-data-with-view-models/

**Comment by JeffreyDavidson** [comment]
@freekmurze  The problem I think I have with this though is the component itself a date-time field that is reused for multiple forms. One of the forms that uses this component has a parent context tag surounding so it knows the model so it know its field's values correctly. I don't want to have this logic inside of this component and with the suggestion above I don't think would apply in this instance is because the $employee->employment->started_at won't be for all of the ViewModel that would get attached to this component.
