### ISSUE TITLE
Attribute Inheritance

### ISSUE THREAD

**Issue by imliam** [spatie/laravel-blade-x#109]
It would be nice to let attributes passed into the component be able to automatically be inherited in the root element of the component.

Say we have a component `x-button` defined with BladeX:

```html
<button>{{ $slot }}</button>
```

We may use it like so:

```html
<x-button class="btn btn-primary">Click me!</button>
```

However, since we didn't explicitly declare how the "class" variable should be used within the component, it isn't used at all in the final rendered HTML.

Unfortunately, this makes the package feel very unnatural to write HTML with, or even coming from something like Vue which has this concept of "[non-prop attributes](https://vuejs.org/v2/guide/components-props.html#Non-Prop-Attributes)" that supports this exact behaviour - as BladeX would force you to explicitly declare every possible attribute that could go on an element, just to make using the component itself feel like HTML.

I'm not entirely sure how this could be implemented into BladeX since it doesn't keep its own list of props used in the current component as Vue does. My initial idea would be to use something like `get_defined_vars()` in scope and converting the appropriate values to a string of HTML attributes that can be output on the root element (or even a sub-element manually using a directive?)

```php
$variablesInScope = get_defined_vars();
$except = ['__path', '__data', '__env', 'obLevel', 'app', 'errors', 'slot'];
$attributes = array_filter($variablesInScope, fn ($key) => !in_array($key, $except), ARRAY_FILTER_USE_KEY);

// Convert $attributes array to a string of HTML attributes?
```

Unfortunately, this approach means _everything_ will be added as an attribute, which probably isn't the intention of the developer. I'm not sure if there would be any decent way to filter it down any further.

Just opening this issue as a discussion - does anyone have any ideas for a better approach? Is this even behaviour you would want to be available in BladeX?

**Comment by imliam** [comment]
Just had the thought that perhaps any attribute with a certain prefix could automatically be passed through, perhaps? Would mean not every variable in scope will get applied to the root element, but still feels fairly natural when writing HTML (after all, we already have to use the colon prefix with Blade-X).

For example:

```html
<x-button !class="btn btn-primary"> ... </x-button>
```

**Comment by freekmurze** [comment]
We will not be investing any more time in this package, as Laravel 7 will have native blade components.
