### ISSUE TITLE
Multiple Prefixes

### ISSUE THREAD

**Issue by mojtabaahn** [spatie/laravel-blade-x#111]
Hi there, Nice stuff 🙌

I was thinking it would be good if it was possible to have **multiple prefixes for multiple purposed components**. like `layout-...` , `partial-...`, `component-...` and more ..

If you think use-case is logical, i can make a PR and adding an **optional second parameter** to `component` and `components` methods as prefix.

**Comment by freekmurze** [comment]
Laravel 7 will have support for a Blade X like syntax. We are not adding any new features to our package anymore.

**Comment by mojtabaahn** [comment]
Well that seems awesome! Is there any resources out yet to read about Laravel 7?
