### ISSUE TITLE
Move away from the XmlSnapshotDriver for tests

### ISSUE THREAD

**Issue by AlexVanderbist** [spatie/laravel-blade-x#114]
For #112 we'd like to move away from the `XmlSnapshotDriver` to something that would support having attributes like this: `...$variable`. 

The phpunit-snapshot package also supports an `HtmlSnapshotDriver` that might be more flexible. Otherwise we might have to good old text-based snapshots.

**Comment by Gummibeer** [comment]
For #112 we don't need a switch.

**Comment by AlexVanderbist** [comment]
In that case, let's not bother. Tests were failing for that HTML driver anyways 😅
