### ISSUE TITLE
Ugly Livewire attributes

### ISSUE THREAD

**Issue by mokhosh** [spatie/laravel-blade-x#116]
Sometimes in livewire attributes you have to combine static string with blade rendered text. Like this:
```html
<button wire:click="edit({{ $language->id }})">edit</button>
<!-- produces this: -->
<button wire:click="edit(1)">edit</button>
```

If it was just the variable we could have used a `:action` attribute on our blade-x element, but now we have to write something like this:
```html
<edit-button :action="'edit('.$language->id.')'"></edit-button>
```
I've red this issue https://github.com/spatie/laravel-blade-x/issues/52 but double quotes inside single quotes is just as messy, and using slots for attributes doesn't seem like the best solution either. Can we do anything to make this a bit more strait forward?

**Comment by freekmurze** [comment]
We will not be investing any more time in this package, as Laravel 7 will have native blade components.
