### ISSUE TITLE
Problem with Vue...?

### ISSUE THREAD

**Issue by telkins** [spatie/laravel-blade-x#27]
Hello,

I'm using Vue and, as such, I'm also employing the prefix per the docs.  Nevertheless, I get the following warning when I hit my page:
>[Vue warn]: Unknown custom element: <x-layout-default-base> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

I'm a little weak on Vue but it's been working fine before beginning to use this package.  I'm wondering if I'm missing something that I need to do with either Vue or BladeX...or both.

Any suggestions...?

Thanks.  :-)

**Comment by freekmurze** [comment]
Do you see any of the BladeX component in the html output of your app? If so you probably did something wrong registering that one.

If you don't see any BladeX component you configured it right and you probably did something wrong at the Vue end.

**Comment by telkins** [comment]
@freekmurze Thx.  I'll take a look and see what I can find.  I haven't dug that deep...yet.  :-)

**Comment by telkins** [comment]
@freekmurze Thx.  I see `<x-layout-default-base>` (the prefixed component name) when I view source, so it sounds like I've registered it incorrectly.  Will take a close(r) look and update when I've found something.

**Comment by telkins** [comment]
@freekmurze OK.  It looks like the docs I'm following are not supported by the code I'm using.  It's also possible I'm using the wrong version.

Anyway, I'm registering my components like so: `BladeX::components('components');`

The code is then looking to see if `components` is a directory...which it's not.

The docs say the following:
```
// This will register all Blade views that are stored in `resources/views/components`

BladeX::components('components')
```

So, it seems that BladeX is not prepending the submitted directories with `resources/views/`.

Is there an error in the code (should it prepend each submitted directory by doing something like `resource_path('views/' . $directory);`...?  Or is there an error in the docs...?

I'm happy to contribute, but I need to know if you have a preference.  To me, it seems that requiring the user to precisely specify the folder gives more flexibility, meaning that the docs should be updated.  Just my 2 cents, though.  :-)

Let me know....

**Comment by telkins** [comment]
@freekmurze OK.  Quick question....

I had assumed that if I had a component in the following file: `resources/views/layouts/default.blade.php`

Then when I registered the `layouts` directory, then I would be able to reference the "component" like so: `<layouts-default>`.

It looks like I was wrong in this assumption and that I should instead reference the "component" like so: `<default>`.

So...are there any plans/wishes to support subfolders (in such a way that the folder name becomes part of the component name)...?

(If I'm unclear about anything, please let me know.)

**Comment by telkins** [comment]
I can already see some (minor) issues with what I've suggested.  Basically, I would have wanted the directory name to be the first piece of the "usage" name....but that wouldn't always be desired...even for me.  There's an easy solution for what I would want, however, in that I can simply restructure my components directories.

There may be other issues, but it still seems reasonable to me to use the folder names as part of the name from and not including the "root" folder.

So...having this file: `resources/views/components/layouts/default.blade.php`

And registering the `components` directory....

Would leave me with a component that I could use like so: `<layouts-default>`.

Thoughts...?

**Comment by freekmurze** [comment]
> Would leave me with a component that I could use like so: <layouts-default>.

Holding off this idea for now, might revisit it later.

Closing this issue because there aren't any interop problems with Vue. If you have more questions, feel free to open up a new issue.
