### ISSUE TITLE
Order of BladeX Component instantiation matters

### ISSUE THREAD

**Issue by snellingio** [spatie/laravel-blade-x#36]
So I have I component within a component to deal with breadcrumbs:

```
<tw-breadcrumb-group>
    <tw-breadcrumb href="#">
        Link 1
    </tw-breadcrumb>
    <tw-breadcrumb href="#">
        Link 2
    </tw-breadcrumb>
    <tw-breadcrumb href="#" active="true">
        Link 3
    </tw-breadcrumb>
</tw-breadcrumb-group>
```

In my AppServiceProvider, I have the following BladeX Components defined:

```
public function boot()
{
    [...]

    BladeX::component('_components.breadcrumb', 'tw-breadcrumb');
    BladeX::component('_components.breadcrumbgroup', 'tw-breadcrumb-group');

```

This errors!

```
/vendor/spatie/laravel-blade-x/src/Exceptions/CouldNotParseBladeXComponent.php

Could not parse a usage of BladeX component `tw-breadcrumb` that uses the `_components/breadcrumb` view because of invalid html. Html found: `<tw-breadcrumb-group></tw-breadcrumb>
```

What is odd is that if I reverse them in the boot method, it works without errors. 

So this works!
```
public function boot()
{
    [...]

    BladeX::component('_components.breadcrumbgroup', 'tw-breadcrumb-group');
    BladeX::component('_components.breadcrumb', 'tw-breadcrumb');

```

For right this second, I've just fixed the ordering in my app. But it would be nice if the ordering didn't error. Especially since the invalid html error is not clear at all.

**Comment by freekmurze** [comment]
Would you mind PR'ing a failing test for us to fix?

**Comment by AlexVanderbist** [comment]
Looks like we're accidentally replacing the wrong `</tw-breadcrumb-group>` closing tag as they both start with `</tw-breadcrumb`... I'll look into this tomorrow.

**Comment by freekmurze** [comment]
Added this test in an attempt to recreate the problem: https://github.com/spatie/laravel-blade-x/blob/5a7e7b41f0658068c1841208a2853616f65cae48/tests/Features/ComponentCompilation/ComponentCompilationTest.php#L140-L147

I can't seem to recreate this problem...

**Comment by AlexVanderbist** [comment]
Just had a look at this again, can't seem to replicate this either. It might've already been fixed on the master branch. I'd suggest waiting until we tag a new version later today and checking if the issue still exists :)

**Comment by snellingio** [comment]
I can confirm updating to `1.2.1` this issue no longer exists. 

Best,
Sam
