### ISSUE TITLE
Multiple version of same component possible?

### ISSUE THREAD

**Issue by RicLeP** [spatie/laravel-blade-x#48]
I’ve not dug into BladeX yet but is it possible to have multiple ways to render the same component? For instance parsing the template as normal, or when logged in as an admin? It would be cool to use this in a CMS where editable controls can be added in some states.

**Comment by freekmurze** [comment]
Inside a component you can do any check you want.

Another way to go about this (if you really want to have separate components for admin/normal user) you could just register another component with the same tag name in the service provider depending on the type of user that is logged in.

**Comment by sebastiandedeyne** [comment]
I'd stay away from using the same name in different context.

BladeX doesn it's work when the views are compiled, while the user check needs to happen at runtime. You'll definitely run into caching issues going down this road.

Ad Freek suggested, I'd do the check inside the component. An alternative solution would be to split the component into three parts. Consider a sidebar that needs to render differently for users and admins:

```html
<sidebar>
    ...
</sidebar>
```

Inside `sidebar.blade.php`:

```html
@if(Auth::user()->isAdmin())
    <admin-sidebar>
        {{ $slot }}
    </admin-sidebar>
@else
    <user-sidebar>
        {{ $slot }}
    </user-sidebar>
@endif
```

This way you still have the single sidebar when using it, but completely separate components in the implementation :)
