### ISSUE TITLE
Attribute interpolation

### ISSUE THREAD

**Issue by rodrigopedra** [spatie/laravel-blade-x#52]
Hi, is there a way to do attribute interpolation?

Assume this simple component:

~~~blade
{{-- components/myComponent.blade.php --}}
<div>{{ $attribute }}</div>
~~~

I want to do this:

~~~blade
<my-component attribute="This should be {{ $interpolated }}"></my-component>
~~~

Currently the output **on screen** is:

~~~html
This should be <?php echo e($interpolated); ?>
~~~

I didn't look into the code, but I guess the compiler is escaping the output before generating the blade file.

As a workaround, I am doing this:

~~~blade
<my-component :attribute="'This should be ' . $interpolated"></my-component>
~~~

**Comment by sebastiandedeyne** [comment]
That's not a workaround, it's how it should be done :)

To clean things up, you could swap the single and double quotes and use PHP string interpolation:

```blade
<my-component :attribute='"This should be $interpolated"'></my-component>
```

Or if you need more templating options, a slot might be a better choice.

```blade
<my-component>
    <slot name="attribute">
        This should be {{ $interpolated }}
    </slot>
</my-component>
```

**Comment by rodrigopedra** [comment]
Ok, thanks!
