### ISSUE TITLE
Recommended spot to put View Models?

### ISSUE THREAD

**Issue by snellingio** [spatie/laravel-blade-x#53]
More of a question than an issue. 

What the is the best practice around namespacing / folder structure for view models?

Something like `App/ViewModels` or `App/Http/ViewModels`?

What about ones specifically for components? `App/.../ViewModels/BladeX` or `App/.../ViewModels/Components`?

Just looking for some opinions, as there is no right or wrong answer.

**Comment by freekmurze** [comment]
In the project I'm working on I've put them in `app\Http\ViewModels\Components`.  In that project we use [regular view models](https://github.com/spatie/laravel-view-models) as well. That's why there is that final `Components` subdirectory.
