### ISSUE TITLE
View not found error when prop is empty

### ISSUE THREAD

**Issue by snellingio** [spatie/laravel-blade-x#59]
Ran into this today:

```
<tw-form-input name="name" placeholder=""></tw-form-input>
```

Throws the following error:
`ErrorException (E_ERROR) View [] not found.`

However:
```
<tw-form-input name="name" placeholder="Your name"></tw-form-input>
```

Works totally fine.

Will investigate and create a PR with tests later this weekend if I have time

**Comment by AlexVanderbist** [comment]
Fixed in v2.0.3!
