### ISSUE TITLE
Error in registration

### ISSUE THREAD

**Issue by coding-sunshine** [spatie/laravel-blade-x#6]
My rierctory structure is resources/views/components/delete.blade.php

when I try to register component in boot method

```
    public function boot()
    {
       BladeX::component('delete', 'components.delete');
    }
```
its giving me following error
```
Could not register component `components.delete` because view `delete` was not found. 
```

 but I can confirm that the view delete.blade.php exists

**Comment by freekmurze** [comment]
Could you PR a failing test for this?

**Comment by coding-sunshine** [comment]
Hi Sorry if I sound dumb, but not having much idea about TDD Packages. So not sure how to do this. I can provide code example though. :(

**Comment by coding-sunshine** [comment]
Here is App service provider, directory structure and error screenshot if it helps.

[code and screens.zip](https://github.com/spatie/laravel-blade-x/files/2431631/code.and.screens.zip)

**Comment by coding-sunshine** [comment]
Thanks very much. 💯

**Comment by coding-sunshine** [comment]
Hi, Sorry, but I am still facing the same issue. I re-installed dev-master branch from scratch and followed the same steps in the readme.

**Comment by coding-sunshine** [comment]
works when I do 
\BladeX::components(resource_path('views/components'));
