### ISSUE TITLE
Not registering correctly if used in a package

### ISSUE THREAD

**Issue by jfsullivan** [spatie/laravel-blade-x#60]
I have a package (PageBuilder) that I want to use BladeX in but components aren't registering correctly.  I have added the following into my package's ServiceProvider...
```
        BladeX::component([
            'page-builder::components.blocks.*',
            'page-builder::components.headers.*',
            'page-builder::components.widgets.myText'
         ]);

         BladeX::prefix('x');
```

The components in the blocks and headers directories are not registering even though I have "*" in the registration paths.  The myText component that I register directly by name is registering but not with the prefix (x).  It displays correct with a <my-text> tag but not with <x-my-text> as I would expect.

**Comment by freekmurze** [comment]
Using subdirectories in a vendor namespace is currently not supported. I'd accept a fully tested PR that adds this to the package.
