### ISSUE TITLE
Issue with SelectFieldViewModel

### ISSUE THREAD

**Issue by kamov** [spatie/laravel-blade-x#62]
I am trying to create this example:
https://docs.spatie.be/laravel-blade-x/v2/advanced-usage/transforming-data-with-view-models

For this code:

```
<option {!!  $isSelected($value) ? 'selected="selected"' : '' !!} name="{{ $value }}">{{ $label }}</option>
```

I am getting $isSelected is undefined.

I fixed checking directly the $value with $selected in this way:

```
<option {!! $value === $selected ? 'selected="selected"' : '' !!} name="{{ $value }}">{{ $label }}</option>
```

However, I would like to know why function isSelected of SelectFieldViewModel is not found.

Thanks

**Comment by freekmurze** [comment]
Our tests prove that this functionality is working properly. 
https://github.com/spatie/laravel-blade-x/blob/master/tests/Features/ViewModel/ViewModelTest.php

Could you submit a failing test for us to look at?

**Comment by kamov** [comment]
It work fine now. Not sure where was the problem. Maybe cache. As I don't change anything, and then it worked fine.
