### ISSUE TITLE
First Usage according to documentation not working?

### ISSUE THREAD

**Issue by Sixosable** [spatie/laravel-blade-x#66]
What I basically did is copy and past the things from the documentation and adjusted them.

[Image can be found here](https://i.gyazo.com/71f6392f292cf3478d120d54efa655d6.png)

Straight up give the error shown in the image.

Here's the code of my AppProvider:
[Image here](https://i.gyazo.com/c10e49b7e423bdf114b8592ec690e2fd.png)
(Added as Image as GitHub was being annoying with the formatting)

**Comment by freekmurze** [comment]
You forgot to import the BladeX facade.
