### ISSUE TITLE
Access variable :model 

### ISSUE THREAD

**Issue by kamov** [spatie/laravel-blade-x#68]
If I create a component like:

```php
<my-form :model="$user" method="post" :action="route('update')">

....

</my-form>

```

Then how I can access variable ":model" ? It not work if I use $model->...

Should it bind automatically to form's input name? Because if yes then not work correctly in my case.

**Comment by sebastiandedeyne** [comment]
Please provide a full example of the above code, and the contents of `my-form.blade.php`.

**Comment by kamov** [comment]
The problem was that I am trying to use $model variable inside another component that is load inside my-form component, something like:

```
<my-form :model="$user" method="post" :action="route('update')">

<my-input />

</my-form>

```

Using $model inside component my-input seem not work. Maybe I need to pass it again to my-input like 
`<my-input :model="$model" />`

**Comment by sebastiandedeyne** [comment]
Yes, variables must be passed explicitly in Blade components.

If you want to implicitly pass something down, look into context: https://docs.spatie.be/laravel-blade-x/v2/advanced-usage/sharing-data-with-context

**Comment by kamov** [comment]
Awsome, context is exactly what I was looking for. 

Thank you
