### ISSUE TITLE
Can't get it work with Laravel modules

### ISSUE THREAD

**Issue by ckissi** [spatie/laravel-blade-x#73]
I'm trying to use laravel-blade-x with "Laravel modules" package but can't get it to work.

My app service provider boot method looks like this:

```
public function register()
    {
        $this->loadViewsFrom(base_path().'/Modules/MyModule/Resources/views','mymodule');

        \BladeX::component([
            'mymodule::components.*'          
        ]);
    }
```

I get no error message, so it seems like it registers the components. 

In the view I use this:
```
<div class="col-lg-9">
     <alert type="error" message="test" />
</div>
```

Unfortunately, the code is left untouched after access and I see this in the rendered HTML file.

`<alert type="error" message="test"></alert>`

I've tried `php artisan view:clear ` . Didn't help.

When I place the component to regular laravel views folder it works OK.

**Comment by dinhquochan** [comment]
You should call element tag with namespace.

```blade
<mymodule::alert ...>
    ...
</mymodule::alert>
```

**Comment by brendt** [comment]
Feel free to send a PR!
