### ISSUE TITLE
Component replaces wrong HTML tag when both start with the same name

### ISSUE THREAD

**Issue by sebastiaanluca** [spatie/laravel-blade-x#74]
In a view, we're using some simple Vue components:
```html
<budget-input></budget-input>
<budget-date-range-picker ></budget-date-range-picker>
```

In our `BladeServiceProvider`, we register a completely different BladeX component:
```php
BladeX::component('components.content.Budget')->tag('budget')->viewModel(BudgetViewModel::class);
```

This results in an error, because BladeX tries to replace all Vue components that start with the `budget` tag/name/string:
```
View [] not found.
```

Similar to https://github.com/spatie/laravel-blade-x/issues/36 and https://github.com/spatie/laravel-blade-x/issues/59.

A quick and easy solution would be to prefix BladeX components, but IMO it remains a bug nonetheless. I'd be happy to submit a PR if pointed in the right direction!

***

My RegEx voodoo skills are inadequate to add the correct check 😄 Need to prevent the rest of the tag name from being tagged as an attribute in the regex pattern:

```
$pattern = "/<\s*{$prefix}{$component->tag}(?<attributes>(?:\s+[\w\-:]+(=(?:\\\"[^\\\"]*\\\"|\'[^\']*\'|[^\'\\\"=<>]+))?)*\s*)(?<![\/=\-])>/";
```

**Comment by AlexVanderbist** [comment]
Thanks! Let's continue this issue in the PR :)

**Comment by AlexVanderbist** [comment]
@sebastiaanluca can you confirm 2.2.1 fixes this issue?

**Comment by sebastiaanluca** [comment]
Like a charm! Thanks for the quick response and improved fix :)
