### ISSUE TITLE
Assign slot directly to component

### ISSUE THREAD

**Issue by derheyne** [spatie/laravel-blade-x#77]
I would be really handy to be able to assign slots directly to components instead of using the `<slot name="whatever">` syntax.

It could look like `<component #whatever>` or `<component x-slot="whatever">`.

## Example behaviour

Blade-X template:

```html
<parent-component>
    <sub-component-1 #someSlot />
    <sub-component-2 x-slot="anotherSlot">
        Hello World!
    </sub-component-2>
</parent-component>
```

Compiled Blade template:

```blade
@component('components.parent-component')
    @slot('someSlot')
        @component('components.sub-component-1')@endcomponent
    @endslot

    @slot('anotherSlot')
        @component('components.sub-component-2')
            Hello World!
        @endcomponent
    @endslot
@endcomponent
```

**Comment by freekmurze** [comment]
We're going to keep things simple and leave things as they are for now.
