### ISSUE TITLE
Cannot install package

### ISSUE THREAD

**Issue by KurtPfund** [spatie/laravel-blade-x#81]

**Comment by KurtPfund** [comment]
I saw your presentation at Laracon.
It was excellent and I have been looking forward to using Blade X on a new project.

I attempted to install it (the project was laravel 5.8.26), and was unable.
I updated to 5.8.31 and encountered the same problem.
Here is my attempt and composer's response:
composer require spatie/laravel-blade-x:^2.0.0
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for spatie/laravel-blade-x 2.0.0 -> satisfiable by spatie/laravel-blade-x[2.0.0].
    - Conclusion: remove laravel/framework v5.8.31
    - Conclusion: don't install laravel/framework v5.8.31
    - spatie/laravel-blade-x 2.0.0 requires illuminate/view ~5.5.0|~5.6.0|~5.7.0 -> satisfiable by illuminate/view[5.5.x
-dev, 5.6.x-dev, 5.7.17, 5.7.18, 5.7.19, 5.7.x-dev, v5.5.0, v5.5.16, v5.5.17, v5.5.2, v5.5.28, v5.5.33, v5.5.34, v5.5.35
, v5.5.36, v5.5.37, v5.5.39, v5.5.40, v5.5.41, v5.5.43, v5.5.44, v5.6.0, v5.6.1, v5.6.10, v5.6.11, v5.6.12, v5.6.13, v5.
6.14, v5.6.15, v5.6.16, v5.6.17, v5.6.19, v5.6.2, v5.6.20, v5.6.21, v5.6.22, v5.6.23, v5.6.24, v5.6.25, v5.6.26, v5.6.27
, v5.6.28, v5.6.29, v5.6.3, v5.6.30, v5.6.31, v5.6.32, v5.6.33, v5.6.34, v5.6.35, v5.6.36, v5.6.37, v5.6.38, v5.6.39, v5
.6.4, v5.6.5, v5.6.6, v5.6.7, v5.6.8, v5.6.9, v5.7.0, v5.7.1, v5.7.10, v5.7.11, v5.7.15, v5.7.2, v5.7.20, v5.7.21, v5.7.
22, v5.7.23, v5.7.26, v5.7.27, v5.7.28, v5.7.3, v5.7.4, v5.7.5, v5.7.6, v5.7.7, v5.7.8, v5.7.9].

And it goes on for a while.

Below is my composer.json - I have replace part of some paths with a ~ for comfort:
{
    "name": "laravel/laravel",
    "type": "project",
    "description": "The Laravel Framework.",
    "keywords": [
        "framework",
        "laravel"
    ],
    "license": "MIT",
    "require": {
        "php": "^7.1.3",
        "fideloper/proxy": "^4.0",
        "genealabs/laravel-caffeine": "^0.8.1",
        "khill/lavacharts": "3.1.*",
        "laravel/framework": "5.8.*",
        "laravel/tinker": "^1.0",
        "laravelcollective/html": "~5.0",
        "phpoffice/phpspreadsheet": "^1.8",
        "riverskies/laravel-mobile-detect": "^1.3"
    },
    "require-dev": {
        "barryvdh/laravel-debugbar": "^3.2",
        "beyondcode/laravel-dump-server": "^1.0",
        "filp/whoops": "^2.0",
        "fzaninotto/faker": "^1.4",
        "mockery/mockery": "^1.0",
        "nunomaduro/collision": "^2.0",
        "phpunit/phpunit": "^7.0"
    },
    "config": {
        "optimize-autoloader": true,
        "preferred-install": "dist",
        "sort-packages": true
    },
    "extra": {
        "laravel": {
            "dont-discover": []
        }
    },
    "autoload": {
        "psr-4": {
            "App\\": "app/"
        },
        "files": [
            "~/codebase.php",
            "~/config.php"
        ],
        "classmap": [
            "database/seeds",
            "database/factories",
            "~/codebase/phpclasses",
            "~/codebase/php7"
        ]
    },
    "autoload-dev": {
        "psr-4": {
            "Tests\\": "tests/"
        }
    },
    "minimum-stability": "dev",
    "prefer-stable": true,
    "scripts": {
        "post-autoload-dump": [
            "Illuminate\\Foundation\\ComposerScripts::postAutoloadDump",
            "@php artisan package:discover --ansi"
        ],
        "post-root-package-install": [
            "@php -r \"file_exists('.env') || copy('.env.example', '.env');\""
        ],
        "post-create-project-cmd": [
            "@php artisan key:generate --ansi"
        ]
    }
}

Any assistance would be appreciated!
Thank you!

**Comment by freekmurze** [comment]
Try requiring v2.2
