### ISSUE TITLE
Better support for packages

### ISSUE THREAD

**Issue by gjm** [spatie/laravel-blade-x#82]
I want to register a set of components from a `ui` package:
```php
BladeX::component('ui::components.*')
```
As an example, if I have a `panel` component it will be registered with the `ui::panel` tag. AFAIK looking at the code, this a feature to prevent name clash, correct? 

Would be great if we could have the possibility to omit the package prefix or, at least, convert it to kebab case (`ui-panel`).

I know I can specify the tag for each component but that would force me to register each one manually. 

Maybe something like:
```php
BladeX::component('ui::components.*')->prefix('ui');  // would prefix with 'ui-'
BladeX::component('ui::components.*')->noPrefix();  // place components in "global" namespace
```

**Comment by freekmurze** [comment]
Feel free to PR this. Make sure to add some tests.

**Comment by Gummibeer** [comment]
Just to clarify, should the current `ui::panel` tag be possible in any registration scenario?

So like:
```php
BladeX::component('ui::components.*'); // <ui::panel>
BladeX::component('ui::components.*')->prefix('ui'); // <ui-panel>
BladeX::component('ui::components.*')->noPrefix(); // <panel>
```

Or should we add a second method `->noNamespace()` which could be combined with the prefix ones and would result in: 
```php
BladeX::component('ui::components.*'); // <ui::panel>
BladeX::component('ui::components.*')->prefix('ui'); // <ui-ui::panel>
BladeX::component('ui::components.*')->noNamespace(); // <panel>
BladeX::component('ui::components.*')->noNamespace()->prefix('ui'); // <ui-panel>
```

Or should we simply add a `->namespaceSeparator()` method to use `-` instead of `::` or any other character wanted?

I miss a bit the real goal of this issue? I get the "problem" but don't see the final wanted solution.

**Comment by gjm** [comment]
@Gummibeer I think the second solution would solve my problem. I could simply register with
```php
BladeX::component('ui::components.*')->noNamespace();
```
and combine with `prefix()` if needed.

**Comment by Gummibeer** [comment]
@freekmurze any thoughts? The naming should be `withoutNamespace()` to follow laravel style!?

**Comment by freekmurze** [comment]
```
BladeX::component('ui::components.*')->noNamespace();
```

seems good. 

> The naming should be withoutNamespace() to follow laravel style!?

Yup!

**Comment by Gummibeer** [comment]
An idea: wouldn't `withoutPackage()` or `withoutPackagePrefix()` be better to prevent conflicts/misunderstandings with PHP namespaces?

**Comment by Gummibeer** [comment]
Will start to work on this now.

**Comment by freekmurze** [comment]
Nice, thanks @Gummibeer 👍 Have fun!

**Comment by gjm** [comment]
Thanks @Gummibeer. Will be following this issue.

**Comment by Gummibeer** [comment]
@freekmurze have already found the first not so easy parts. Atm we only have one global prefix. Will add the ability to prefix every single component/collection at the same time.

```php
BladeX::prefix('x');
BladeX::component('alert'); // <x-alert>
BladeX::registerComponents('ui::components.*')->withoutNamespace()->prefix('ui'); // <ui-panel>
BladeX::component('panel')->prefix('app'); // <app-panel>
```

This isn't possible atm but I need something pretty similar to accomplish the request. SO I will pass this feature to the user.

**Comment by Gummibeer** [comment]
@freekmurze is it right/wanted that if I register `BladeX::component('ui::alert')` it will not prefix it with `ui::`. Only if I register `BladeX::component('ui::components.alert')` it will get the namespace prefix.

```php
$view = 'ui::alert';
$tag = 'ui::alert';

Str::contains($view, '::'); // true
! Str::contains($tag, '::') // ! true

/* ----- */

$view = 'ui::components.alert';
$tag = 'alert';

Str::contains($view, '::'); // true
! Str::contains($tag, '::') // ! false
```

https://github.com/spatie/laravel-blade-x/blob/7f604ebd9dedf6078c8c331c966bccae57e7c5fb/src/Component.php#L65-L68

For me this feels wrong - but in theory this would be BC to change/fix it. But why should a package component not in a subdirectory don't get a namespace prefix?

**Comment by Gummibeer** [comment]
@gjm could you check the PR and tell me if this is what you wanted? You have to use `components()` (plural) now to register multiple components, get a `ComponentCollection` (not `null` as return and be able to chain the added methods.

**Comment by freekmurze** [comment]
We'll continue this on #84

**Comment by gjm** [comment]
@Gummibeer how can I test the code? Can't clone your fork...
