### ISSUE TITLE
Allow to register subdirectories

### ISSUE THREAD

**Issue by Gummibeer** [spatie/laravel-blade-x#85]
At the moment the `*` wildcard only resolves one level. So I would have to have all components in a single component folder or register every single subfolder by its own.

It would be great to support a multi level wildcard. Something like `components.**` or the also known `components.**.*`.

This would allow more structure in larger component collections without the need to add every folder to the service provider.

**Comment by freekmurze** [comment]
It's a nice suggestion, but we haven't got a need for this ourselves at this moment and there were no issues previously that were asking for this.

Do you need this in a real life project?

**Comment by Gummibeer** [comment]
Yes, we splitted our views in really really small components - like recommended for Vue/React setups.
So we have a base input and extending for every type, these get wrapped by form components which again get wrapped by forms which get wrapped by a card which extends a basic card and so on.

This gives a lot of flexibility but only works good if the components are well structured.
Atm we have a workaround which globs all directories and calls the `component()` method in a loop to prevent changes to the service provider all the time.
But having a simple `**.*` and let the package does the work would be better.

**Comment by freekmurze** [comment]
OK, send a PR for this. Thanks! 👍

**Comment by Gummibeer** [comment]
Could you keep the issue open. This will make it easier for me to keep track of my open todo here. 😊

**Comment by Gummibeer** [comment]
Will use #84 as base for this to prevent double and merge work.

**Comment by Gummibeer** [comment]
discussion will follow in #86
