### ISSUE TITLE
use spatie/laravel-view-models instead of copy'n'paste

### ISSUE THREAD

**Issue by Gummibeer** [spatie/laravel-blade-x#89]
The `ViewModel` class in this package is identical to the [spatie/laravel-view-models](https://github.com/spatie/laravel-view-models) package except that it isn't responsable, which is an optional feature.
So it would be good require the package instead of duplicate work.

**Comment by freekmurze** [comment]
I tend to try to minimize the dependencies of a package and prefer to just use a lightweight version of just the things we need.

If there's ever a real need to require the view-models package, I'll do it. But for now, I think it's fine.
