### ISSUE TITLE
Let attributes cascade

### ISSUE THREAD

**Issue by driesvints** [spatie/laravel-blade-x#94]
I didn't find an issue about this so thought to open one about it. This is more of a question than a feature request I guess.

From Blade I'm used that variables which are passed to includes are cascaded down into includes inside includes. With Blade components you need to explicitly set anything you want to cascade through.

For example:

**login.blade.php**

```php
<x-checkbox-field field="remember" :label="__('Remember Me')" />
```

**checkboxField.blade.php**

```php
<div>
    <input type="checkbox" name="{{ $field }}" id="{{ $field }}" {{ old($field) ? 'checked' : '' }}>

    <x-label :field="$field" :label="$label" />
    <x-error :field="$field" />
</div>
```

**label.blade.php**

```php
<label for="{{ $field }}">
    {{ $label }}
</label>
```

My question: why do I need to define `<x-label :field="$field" :label="$label" />` instead of just `<x-label />`? I'm okay with doing it explicitly but was just wondering about the difference in behavior from the `@include` tag.

**Comment by freekmurze** [comment]
This package tries to mimic how things are done in a front end framework like Vue. There, you need to pass variables explicitly down.

Not 100% sure, but I think `context` might cascade down: https://docs.spatie.be/laravel-blade-x/v2/advanced-usage/sharing-data-with-context/
