### ISSUE TITLE
Update Laravel version requirement to 5.8 or higher

### ISSUE THREAD

**Issue by markstaun** [spatie/laravel-blade-x#95]
Since version 2.2 the laravel minimum requirement Laravel is 5.8 and not 5.6 as stated in the docs

**Comment by freekmurze** [comment]
Feel free to send a PR to correct it.

**Comment by markstaun** [comment]
https://github.com/spatie/laravel-blade-x/pull/96

**Comment by AlexVanderbist** [comment]
Thanks!
