### ISSUE TITLE
Attribute spread operator support

### ISSUE THREAD

**Issue by Gummibeer** [spatie/laravel-blade-x#97]
The idea I have is something like `...attr="$el"` as a replacement for `:class="$el['class']" :src="$el['src']"`. So like the opposite of `compact()`. Or even only `...$el` because I would say that the spreaded attribute name would be ignored anyway.

```
<x-img ...$img />
// vs
<x-img :src="$img['src']" :alt="$img['alt']" :class="$img['class']" />
```

The `$img` variable should be an array or arrayable but has to have strings, which should get kebabed, as keys.

**Comment by AlexVanderbist** [comment]
I like this idea a lot. Gonna check what the rest of the team thinks :)

**Comment by Gummibeer** [comment]
One thing to think about could be the priority. I would say that a specific attribute should override a spreaded array key. So independent of the order in the element the more precise one should override the spreaded one.
What do you think?

**Comment by freekmurze** [comment]
Seems like a great idea to me 👍

**Comment by AlexVanderbist** [comment]
Thanks for your input and work on this! We'll continue this in the PR :)
